linux-arm64:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -GNinja
    - PATH=/usr/lib/ccache:$PATH ninja install
    - ./zig build --build-file ../build.zig test
